version: 2.1

# Orbs
orbs:
  # Node orb
  node: circleci/node@5.0.1
  # Docker orb
  docker: circleci/docker@1.4.0

# Jobs
jobs:
  # Build job
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install

  # Test job
  test:
    docker:
      - image: cimg/node:16.10 # Use a Node image to run tests
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm run test

  # Build and Push job
  build-and-push:
    docker:
      - image: circleci/python:3.7 # Use a Python image to run Docker commands
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - docker/build: # Build the Docker image
          image: "heropahn/circleci_m4" # Name of the Docker image
          tag: "latest" # Tag of the Docker image
          path: "." # Path to the Dockerfile
      - run:
          name: Docker Login
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin # Login to Docker Hub
      - run:
          name: Push Docker Image
          command: docker push $DOCKER_USER/circleci_m4:latest # Push the Docker image to Docker Hub

# Workflows
workflows:
  version: 2
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
