version: 2.1

# Orbs
orbs:
  # Node orb
  node: circleci/node@5.0.1
  # Docker orb
  docker: circleci/docker@1.4.0

# Jobs
jobs:
  # Build job
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Docker Build
          command: docker build -t $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 .

  # Test job
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm run test

  # Build and Push job
  build-and-push:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker Build and Push
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_USER/circleci-demo-docker:$TAG .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/circleci-demo-docker:$TAG

  # Check Docker job
  check-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Check Docker Status
          command: |
            docker version
            docker run hello-world

# Workflows
workflows:
  version: 2
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - check-docker:
          requires:
            - build-and-push
