version: 2.1

# YAML takes indentation very seriously.

# Orbs
orbs:
  # Node orb
  node: circleci/node@5.0.1
  # Docker orb
  docker: circleci/docker@1.4.0

# Jobs
jobs:
  # Build job
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: | # | means multiline
          echo "Installing dependencies..."
          npm install

  # Test job
  test:
    docker:
      - image: cimg/node:16.10 # can use a different image for different jobs
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: | # | means multiline
          echo "Running tests..."
          npm run test

  # Build and Push job
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - docker/login:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USER/education-space:$CIRCLE_SHA1 .
            docker tag $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 $DOCKER_USER/circleci_m4:latest
      - docker/push:
          image: $DOCKER_USER/circleci_m4:$CIRCLE_SHA1
      - docker/push:
          image: $DOCKER_USER/circleci_m4:latest

# Workflows
workflows:
  version: 2
  simple_workflow:
    jobs:
      - build # Array of jobs
      - test:
          requires: # Requires build job to be completed successfully
            - build
