version: 2.1

# YAML takes indentation very seriously.

# Orbs
orbs:
  # Node orb
  node: circleci/node@5.0.1

# Jobs
jobs:
  # Build job
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: | # | means multiline
          echo "Installing dependencies..."
          npm install

  # Test job
  test:
    docker:
      - image: cimg/node:16.10 # can use a different image for different jobs
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: | # | means multiline
          echo "Running tests..."
          npm run test

  # Publish job
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Publish Docker Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/$DOCKER_REPO:$CIRCLE_SHA1 .
            docker push $DOCKER_USER/$DOCKER_REPO:$CIRCLE_SHA1
            docker tag $DOCKER_USER/$DOCKER_REPO:$CIRCLE_SHA1 $DOCKER_USER/$DOCKER_REPO:latest
            docker push $DOCKER_USER/$DOCKER_REPO:latest

# Workflows
workflows:
  version: 2
  simple_workflow:
    jobs:
      - build # Array of jobs
      - test:
          requires: # Requires build job to be completed successfully
            - build
