version: 2.1

# Orbs
orbs:
  # Node orb
  node: circleci/node@5.0.1
  # Docker orb
  docker: circleci/docker@1.4.0

# Jobs
jobs:
  # Build job
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install
      # - run:
      #     name: Check Docker Daemon Status
      #     command: sudo systemctl status docker
      # - run:
      #     name: Restart Docker Service
      #     command: sudo systemctl restart docker
      # - run:
      #     name: Check Docker Socket Permissions
      #     command: ls -l /var/run/docker.sock
      # - run:
      #     name: Docker Build
      #     command: docker build -t $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 .

  # Test job
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm run test

  # Build and Push job
  build-and-push:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - docker/build:
          image: "heropahn/circleci_m4"
          tag: "latest"
          path: "."
      - run:
          name: Docker Login
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKER_USER/circleci_m4:latest

# Workflows
workflows:
  version: 2
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
