version: 2.1

# Orbs
orbs:
  # Node orb
  node: circleci/node@5.0.1
  # Docker orb
  docker: circleci/docker@1.4.0

# Jobs
jobs:
  # Build job
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install

  # Test job
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm run test

  # Build and Push job
  build-and-push:
    executor: docker/docker
    steps:
      - checkout
      - docker/check:
          # registry-url: https://index.docker.io/v1/
          username: DOCKER_USER
          password: DOCKER_PASS
      - docker/publish:
          image: "heropahn/circleci_m4"
          tag: "latest"
          # registry-url: https://index.docker.io/v1/
          username: DOCKER_USER
          password: DOCKER_PASS

# Workflows
workflows:
  version: 2
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
